```{r}
library(dplyr)
library(lme4)
library(scales)
library(lmerTest)
library(stringr)
library(purrr)
library(ggplot2)
library(cowplot)
library(tidyverse)
library(emmeans)
library(dunn.test)
library(PMCMRplus)
library(ggpubr)
library(ggsignif)
`%notin%` <- Negate(`%in%`)
current_date <- Sys.Date()
formatted_date <- format(current_date, "%m%d%y")
print(formatted_date)
```

```{r}
df.t0_EU_RNA <- read.csv('../Results/t0/cellprofiler_outputs/rdf_plot_data.csv ') %>% mutate(condition = 't0_EU_RNA', filename = str_extract(treatment, "[^/]+$"))
df.t30_EU_RNA <- read.csv('../Results/t30/cellprofiler_outputs/rdf_plot_data.csv') %>% mutate(condition = 't30_EU_RNA', filename = str_extract(treatment, "[^/]+$"))
df.RDF_data <- bind_rows(df.t0_EU_RNA, df.t30_EU_RNA)
```
```{r}
colnames(df.RDF_data)
print(unique(df.RDF_data$channel))
print(unique(df.RDF_data$filename))
```
```{r}
##make a list of files to ignore due to poor image quality
ignore_list =c("2C10_5Ch_t010tif_5ch_reordered_","2C10_5Ch_t012tif_5ch_reordered_","2C10_5Ch_t015tif_5ch_reordered_","2C10_5Ch_t017tif_5ch_reordered_","2C10_5Ch_t022tif_5ch_reordered_","2C10_5Ch_t030tif_5ch_reordered_",
               "2C10_5Ch_t038tif_5ch_reordered_","2C10_5Ch_t03tif_5ch_reordered_","2C10_5Ch_t041tif_5ch_reordered_","2C10_5Ch_t051tif_5ch_reordered_","2C10_5Ch_t020tif_5ch_reordered_","2C10_5Ch_t025tif_5ch_reordered_",
               "2C10_5Ch_t026tif_5ch_reordered_","2C10_5Ch_t029tif_5ch_reordered_","2C10_5Ch_t031tif_5ch_reordered_",
               "2C10_5Ch_t3020tif_5ch_reordered_","2C10_5Ch_t3025tif_5ch_reordered_","2C10_5Ch_t3026tif_5ch_reordered_","2C10_5Ch_t3029tif_5ch_reordered_","2C10_5Ch_t3031tif_5ch_reordered_","2C10_5Ch_t3033tif_5ch_reordered_",
               "2C10_5Ch_t3034tif_5ch_reordered_","2C10_5Ch_t3037tif_5ch_reordered_","2C10_5Ch_t3038tif_5ch_reordered_","2C10_5Ch_t3039tif_5ch_reordered_","2C10_5Ch_t3041tif_5ch_reordered_","2C10_5Ch_t3043tif_5ch_reordered_",
               "2C10_5Ch_t307tif_5ch_reordered_","2C10_5Ch_t308tif_5ch_reordered_","2C10_5Ch_t309tif_5ch_reordered_")
df.filtered_RDF_data <- filter(df.RDF_data, filename %notin% ignore_list)
```
```{r}
unique(df.filtered_RDF_data$condition)
df.filtered_t0_t30_RDF_data <- filter(df.filtered_RDF_data, condition %in% c('t0_EU_RNA','t30_EU_RNA'))
df.filtered_t0_t30_RDF_plot <- df.filtered_t0_t30_RDF_data %>%
  group_by(channel, distance,condition) %>%
  dplyr::summarize(
    mean_norm_intensity = mean(norm_intensity),
    se_norm_intensity = sd(norm_intensity) / sqrt(n())
  ) %>%
  mutate(
    mean_se_min = mean_norm_intensity - se_norm_intensity,
    mean_se_max = mean_norm_intensity + se_norm_intensity
  )
write.csv(df.filtered_t0_t30_RDF_data, './260216_cleaned_t0_t30_RDF_indiv_traces.csv')
write.csv(df.filtered_t0_t30_RDF_plot, './260216_cleaned_t0_t30_RDF_combined_traces.csv')
```


```{r}
ggplot(df.filtered_t0_t30_RDF_plot %>% filter(condition == "t0_EU_RNA"), aes(x = distance,  y = mean_norm_intensity, color = channel, fill = channel)) +
  geom_ribbon(aes(ymin = mean_se_min, ymax = mean_se_max), alpha = 0.2) +
  geom_line(size = 1) +
  theme_minimal()+
  ggtitle("RDF of t0_EU_RNA_Data:")+
  scale_color_manual(values = c("rRNA" = "magenta",
                                "DFC" = "red",
                                "FC" = "orange",
                                "GC" = "green",
                                "SURF6" = "blue",
                               "SSF1" = 'darkcyan'))+
  scale_fill_manual(values = c("rRNA" = "magenta",
                                "DFC" = "red",
                                "FC" = "orange",
                                "GC" = "green",
                                "SURF6" = "blue",
                               "SSF1" = 'darkcyan'))


ggplot(df.filtered_t0_t30_RDF_plot %>% filter(condition == "t30_EU_RNA"), aes(x = distance,  y = mean_norm_intensity, color = channel, fill = channel)) +
  geom_ribbon(aes(ymin = mean_se_min, ymax = mean_se_max), alpha = 0.2) +
  geom_line(size = 1) +
  theme_minimal()+
  ggtitle("RDF of t30_EU_RNA_Data:")+
  scale_color_manual(values = c("rRNA" = "magenta",
                                "DFC" = "red",
                                "FC" = "orange",
                                "GC" = "green",
                                "SURF6" = "blue",
                               "SSF1" = 'darkcyan'))+
  scale_fill_manual(values = c("rRNA" = "magenta",
                                "DFC" = "red",
                                "FC" = "orange",
                                "GC" = "green",
                                "SURF6" = "blue",
                               "SSF1" = 'darkcyan'))
```





