import pathlib, os

root   = pathlib.Path("..")                 #  points one level up no matter OS
DATA   = root/"data"
RESULT = root/"results"
LOGS   = root/"logs"
BENCH  = root/"benchmarks"
RESRC  = root/"resources"

# Replacing POSIX‑only commands inside *shell* blocks like mkdir
def mkdir(dirpath):
    """Portable directory creation (no '-p', no race)."""
    pathlib.Path(dirpath).mkdir(parents=True, exist_ok=True)

files = glob_wildcards(f"{DATA}/{{experiment_name}}/{{sample}}.tif")

rule all:
    input:
        directory(expand(RESULT/"{experiment}"/"plots", experiment=files.experiment_name)),
        directory(expand(RESULT/"{experiment}"/"cellprofiler_outputs", experiment=files.experiment_name)),
        directory(expand(RESULT/"{experiment}"/"mip", experiment=files.experiment_name))


rule mip:
    input:
        in_dir = directory(DATA/"{experiment}"),
        script = pathlib.Path("scripts") / "mip.py"
    output:
        out_dir = directory(RESULT/"{experiment}"/"mip")
    params:
        channels = 4,
        colors   = "m,r,o,g"
    log:
        LOGS/"{experiment}"/"mip.log"
    threads:
        int(workflow.cores * 0.20)
    # benchmark:
    #     BENCH/"{experiment}"/"mip.tsv"
    run:
        mkdir(output.out_dir)
        
        in_dir  = os.path.normpath(str(input.in_dir))
        out_dir = os.path.normpath(str(output.out_dir))
        log     = os.path.normpath(str(log))
        script = os.path.normpath(str(input.script))

        shell(
            "python {script} "
            "-i {in_dir} "
            "-o {out_dir} "
            "--channels {params.channels} "
            "--lut {params.colors} "
            "--log {log} "
        )

###############################################################################
# 2  CellProfiler
###############################################################################
rule cellprofiler:
    input:
        in_dir     = directory(RESULT / "{experiment}" / "mip"),
        pipeline   = RESRC / "rdf.cppipe",
        plugin_dir = RESRC / "plugins"
    output:
        out_dir = directory(RESULT / "{experiment}" / "cellprofiler_outputs")
    log:
        LOGS / "{experiment}" / "cellprofiler_run.log"
    threads:
        int(workflow.cores * 0.50)
    # benchmark:
    #     BENCH / "{experiment}" / "cellprofiler.tsv"
    run:

        in_dir     = os.path.normpath(str(input.in_dir))
        pipeline   = os.path.normpath(str(input.pipeline))
        plugin_dir = os.path.normpath(str(input.plugin_dir))
        out_dir    = os.path.normpath(str(output.out_dir))
        log        = os.path.normpath(str(log))

        mkdir(output.out_dir)
        shell(
            "cellprofiler -c -r "
            "-p {pipeline} "
            "-i {in_dir} "
            "-o {out_dir} "
            "--plugins-directory {plugin_dir} "
            " > {log} 2>&1"
        )


###############################################################################
# 3  Plotting
###############################################################################
rule plot:
    input:
        input_dir = directory(RESULT / "{experiment}" / "cellprofiler_outputs"),
        script = pathlib.Path("scripts") / "rdf.py"
    output:
        out_dir = directory(RESULT / "{experiment}" / "plots")
    params:
        regex = "t(?P<time>\d+)_(?P<treatment>[^_]+)[\w]*.tif"
    log:
        LOGS / "{experiment}" / "rdf.log"
    threads:
        int(workflow.cores * 0.20)
    # benchmark:
    #     BENCH / "{experiment}" / "rdf.tsv"
    run:
        mkdir(output.out_dir)

        in_dir = os.path.normpath(str(input.input_dir))
        out_dir = os.path.normpath(str(output.out_dir))
        log = os.path.normpath(str(log))
        script = os.path.normpath(str(input.script))

        shell('''
            python {script} \
            --output-dir {out_dir} \
            --input-dir {in_dir} \
            --log-file {log} \
            --regex "{params.regex}"
            '''
        )
 